TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# overrides from configure/CONFIG_COMMON in Base
INSTALL_DB = $(INSTALL_LOCATION)/protocol

DB += hp3458a.proto

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

